# Generated by Django 5.1.2 on 2024-10-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(default="UK", max_length=100),
        ),
    ]
