# Generated by Django 5.1.2 on 2024-10-29 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_county_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="agency",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.agency",
            ),
            preserve_default=False,
        ),
    ]
