# Generated by Django 5.1.2 on 2024-11-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_invitation_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
