# Generated by Django 5.1.2 on 2024-11-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_agency_county"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("staff", "Staff"), ("agency_manager", "Agency Manager")],
                default="staff",
                max_length=20,
            ),
        ),
    ]
