# Generated by Django 5.1.2 on 2024-11-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_invitation_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
