# Generated by Django 5.1.2 on 2024-11-07 02:58

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_profile_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="recovery_codes",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="totp_secret",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
