# Generated by Django 5.1.2 on 2024-11-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_agency_owner_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
