# Generated by Django 5.1.2 on 2024-11-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_agency_stripe_customer_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
