# Generated by Django 5.1.2 on 2024-11-21 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_agency_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_agency",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
