# Generated by Django 5.1.2 on 2024-10-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0002_alter_shift_options_alter_shiftassignment_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shift",
            old_name="state",
            new_name="county",
        ),
    ]
