# Generated by Django 5.1.2 on 2024-11-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0003_rename_state_shift_county"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftassignment",
            name="completion_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="completion_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="completion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
