# Generated by Django 5.1.2 on 2024-11-02 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0005_shift_is_overnight"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Specify the date when the shift ends.",
            ),
        ),
    ]
