# Generated by Django 3.2.25 on 2024-10-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_agency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AddField(
            model_name='shift',
            name='agency',
            field=models.ForeignKey(default='Default Agency', on_delete=django.db.models.deletion.CASCADE, to='shifts.agency'),
            preserve_default=False,
        ),
    ]
