# Generated by Django 5.1.2 on 2024-11-03 18:55

import shifts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0006_shift_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftassignment",
            name="signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="shift_signatures/",
                validators=[shifts.validators.validate_image],
            ),
        ),
    ]
