# Generated by Django 3.2.25 on 2024-10-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_auto_20241012_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
