# Generated by Django 3.2.25 on 2024-10-13 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0009_auto_20241013_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.agency'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('morning_shift', 'Morning Shift'), ('day_shift', 'Day Shift'), ('night_shift', 'Night Shift'), ('bank_holiday', 'Bank Holiday'), ('emergency_shift', 'Emergency Shift')], default='regular', max_length=50),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shift'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
