# Generated by Django 5.1.2 on 2024-11-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_user_email"),
        ("shifts", "0010_alter_shift_end_date"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("agency", "shift_date", "name")},
        ),
    ]
