# Generated by Django 5.1.2 on 2024-11-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0011_alter_shift_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the shift is active and available for assignments.",
            ),
        ),
    ]
