# Generated by Django 5.1.2 on 2024-11-18 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0012_shift_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="shift_code",
            field=models.CharField(
                db_index=True,
                default=django.utils.timezone.now,
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
