# Generated by Django 5.1.2 on 2024-11-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0013_shift_shift_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="shift_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
