# Generated by Django 5.1.2 on 2024-11-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_plan_remove_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="plan",
            name="price_yearly",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
