# Generated by Django 5.1.2 on 2024-11-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_remove_plan_price_yearly"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
