# Generated by Django 5.1.2 on 2024-11-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_plan_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_recommended",
            field=models.BooleanField(default=False),
        ),
    ]
