# Generated by Django 5.1.2 on 2024-11-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_plan_is_recommended"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="is_recommended",
        ),
    ]
