# Generated by Django 5.1.2 on 2024-11-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_remove_subscription_billing_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="advanced_reporting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_staff_members",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="plan",
            name="notifications_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="priority_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
