# Generated by Django 5.1.2 on 2024-11-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0011_plan_advanced_reporting_plan_max_staff_members_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="shift_management",
            field=models.BooleanField(default=False),
        ),
    ]
