# Generated by Django 5.1.2 on 2024-11-12 01:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_agency_stripe_customer_id"),
        ("subscriptions", "0013_alter_plan_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.RemoveField(
            model_name="plan",
            name="features",
        ),
        migrations.AddField(
            model_name="plan",
            name="staff_performance",
            field=models.BooleanField(
                default=False,
                help_text="Enable staff performance tracking for this plan.",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="advanced_reporting",
            field=models.BooleanField(
                default=False,
                help_text="Enable advanced reporting features for this plan.",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                help_text="Billing cycle for the subscription plan.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the subscription plan."
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the plan is active and available for subscription.",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="is_recommended",
            field=models.BooleanField(
                default=False, help_text="Indicates whether the plan is recommended."
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="max_staff_members",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of staff members allowed for this plan.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(
                choices=[
                    ("Basic", "Basic"),
                    ("Pro", "Pro"),
                    ("Enterprise", "Enterprise"),
                ],
                help_text="Name of the subscription plan.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="notifications_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable notifications feature for this plan."
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price of the subscription plan.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="priority_support",
            field=models.BooleanField(
                default=False, help_text="Enable priority support for this plan."
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="shift_management",
            field=models.BooleanField(
                default=False,
                help_text="Enable shift management features for this plan.",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID associated with this plan.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Product ID associated with this plan.",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="view_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of views allowed per month.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="agency",
            field=models.OneToOneField(
                help_text="Agency associated with this subscription.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="accounts.agency",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the subscription was created.",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(
                blank=True,
                help_text="End date of the current billing period.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="current_period_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Start date of the current billing period.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the subscription is currently active.",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_expired",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the subscription has expired.",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                help_text="Subscription plan chosen by the agency.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="subscriptions.plan",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Subscription ID associated with this subscription.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp when the subscription was last updated.",
            ),
        ),
    ]
