# Generated by Django 5.1.2 on 2024-11-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0014_alter_plan_options_alter_subscription_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="max_staff_members",
        ),
        migrations.AddField(
            model_name="plan",
            name="custom_integrations",
            field=models.BooleanField(
                default=False, help_text="Enable custom integrations for this plan."
            ),
        ),
    ]
