# Generated by Django 5.1.2 on 2024-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0015_remove_plan_max_staff_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Product ID associated with this plan.",
                max_length=100,
                null=True,
            ),
        ),
    ]
