# Generated by Django 5.1.2 on 2024-11-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0016_alter_plan_stripe_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="shift_limit",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Maximum number of shifts allowed under this plan.",
            ),
        ),
    ]
