# Generated by Django 5.1.2 on 2024-11-14 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0017_plan_shift_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="shift_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of shifts allowed under this plan. Leave blank for unlimited.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Subscription plan chosen by the agency.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="subscriptions.plan",
            ),
        ),
    ]
