# Generated by Django 5.1.2 on 2024-11-14 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0018_alter_plan_shift_limit_alter_subscription_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                default=51,
                help_text="Subscription plan chosen by the agency.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="subscriptions.plan",
            ),
            preserve_default=False,
        ),
    ]
