# Generated by Django 5.1.2 on 2024-11-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0019_alter_subscription_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                default="",
                help_text="Stripe Subscription ID associated with this subscription.",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
