# Generated by Django 5.1.2 on 2024-11-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_remove_agency_state_remove_profile_state"),
        ("subscriptions", "0020_alter_subscription_stripe_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Subscription ID associated with this subscription.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together={("stripe_subscription_id", "agency")},
        ),
    ]
