# Generated by Django 5.1.2 on 2024-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0021_alter_subscription_stripe_subscription_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("canceled", "Canceled"),
                    ("past_due", "Past Due"),
                    ("unpaid", "Unpaid"),
                ],
                default="inactive",
                help_text="Current status of the subscription.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="current_period_end",
            field=models.DateTimeField(
                help_text="End date of the current billing period."
            ),
        ),
    ]
