# Generated by Django 5.1.2 on 2024-11-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_agency_owner"),
        ("subscriptions", "0022_subscription_status_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("agency",),
                name="unique_active_subscription_per_agency",
            ),
        ),
    ]
